all:
	arm-linux-gnueabi-gcc -g -Wall example1.c  -o ../bin/example1
	arm-linux-gnueabi-gcc -g -Wall example2.c  -o ../bin/example2
	arm-linux-gnueabi-gcc -g -Wall example3.c  -o ../bin/example3

clean:
	rm ../bin/*
